name: Build image on push (branches)

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      IMAGE_BASE: ghcr.io/${{ github.repository }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU (optional)
        uses: docker/setup-qemu-action@v3

      - name: Set up buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push SHA-tag image
        id: build
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./.devcontainer/Dockerfile
          push: true
          build-args: |
            GITHUB_REPOSITORY=${{ github.repository }}
          tags: |
            ${{ env.IMAGE_BASE }}:${{ github.sha }}
          # optionally set platforms if you want multi-arch:
          # platforms: linux/amd64,linux/arm64
